    <!-- main -->
    <main >
      <section style="margin-top:2em; margin-left:2em;" id="section-about">
        <div class="section-about font-rale">
          <h2>About us</h2>
          <hr>
          <p class="font-size-14 font-rubik">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat quod totam cupiditate corporis accusantium, praesentium vel facere placeat minus quas in! Dolores voluptate maxime sunt voluptatibus quod ea assumenda ipsa libero fuga? Iure est cumque sequi cupiditate, fugit sed natus sit saepe ratione temporibus perspiciatis reiciendis veniam, commodi voluptas porro maiores quasi mollitia necessitatibus dolor nemo similique atque veritatis minus expedita. Consequatur nihil quod facilis minus reprehenderit dolore, sint repudiandae maiores quibusdam vel ea omnis adipisci, sit non, magni quasi quia aut laborum. Ullam, beatae. Magnam tempora aliquid sunt. Facere, optio doloribus quidem dolorem corrupti reprehenderit soluta inventore hic provident neque asperiores aperiam blanditiis porro magni possimus culpa error sapiente iste officiis. Nostrum culpa explicabo cum hic adipisci. Tempore quam sint optio. Voluptatem, recusandae. Ex doloremque ea omnis eius? Ipsum incidunt nulla, magnam labore sequi inventore hic soluta quae autem. Quo, molestiae commodi voluptatum voluptatibus ratione veritatis voluptates, totam laborum reiciendis iste odit vel, nulla eos ipsum. Possimus modi est quam ex, corrupti totam sit esse nisi nesciunt iusto quod cum voluptatem nulla, suscipit magnam repellat ipsa maiores earum quis eligendi autem optio laboriosam blanditiis ad. Ut ipsum nostrum et, maiores nulla incidunt similique quia asperiores non sunt assumenda voluptatum aspernatur officiis? Quis accusamus culpa adipisci beatae nulla amet, a ipsam iure reprehenderit doloremque quos obcaecati accusantium aspernatur non fugiat ad eos reiciendis autem asperiores illo. Odio eligendi deleniti facilis magni blanditiis quas nesciunt eveniet repudiandae architecto? Consectetur at vitae blanditiis voluptatibus ipsum natus neque perspiciatis modi ratione. Incidunt, iusto? Temporibus, cumque cupiditate. Error, aut et obcaecati ad aliquam tenetur numquam nobis quas perspiciatis delectus amet aspernatur cum aliquid dolores ea doloribus quibusdam laborum suscipit! Voluptatibus non maxime iusto voluptatem perferendis soluta libero quaerat repellat eveniet quo fugit nostrum numquam doloremque obcaecati mollitia perspiciatis laudantium pariatur ab, id recusandae voluptas hic, facere fuga asperiores. Alias pariatur iure eos odio facere similique blanditiis illo magni. Architecto qui reiciendis magni possimus quisquam, placeat omnis eveniet hic? Similique totam, inventore et neque minus ipsam.</p>
        </div>
      </section>
    </main>
    <!-- !main -->